export enum Country {
    AT = "AT",
    BE = "BE",
    BG = "BG",
    CY = "CY",
    CZ = "CZ",
    DE = "DE",
    DK = "DK",
    EE = "EE",
    EL = "EL",
    ES = "ES",
    FI = "FI",
    FR = "FR",
    HR = "HR",
    HU = "HU",
    IE = "IE",
    IT = "IT",
    LT = "LT",
    LU = "LU",
    LV = "LV",
    MT = "MT",
}